spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.sqlite.JDBC
  artemis:
    mode: embedded
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

frontend-url: ${FRONTEND_URL}

discord:
  token: ${DISCORD_TOKEN}
  application-id: ${DISCORD_APPLICATION_ID}
  guild-id: ${DISCORD_GUILD_ID}
  game-announcement-channel-id: ${DISCORD_GAME_ANNOUNCEMENT_CHANNEL_ID}
  rank-up-announcement-channel-id: ${DISCORD_RANK_UP_ANNOUNCEMENT_CHANNEL_ID}
  member-role-id: ${DISCORD_MEMBER_ROLE_ID}
  admin-role-id: ${DISCORD_ADMIN_ROLE_ID}
  review-mention-role-id: ${DISCORD_REVIEW_MENTION_ROLE_ID}
  oauth:
    client-id: ${DISCORD_OAUTH_CLIENT_ID}
    client-secret: ${DISCORD_OAUTH_CLIENT_SECRET}
    redirect-uri: ${DISCORD_OAUTH_REDIRECT_URI}

goserver:
  kgs:
    url: https://www.gokgs.com/json/access
    username: ${KGS_BOT_USERNAME}
    password: ${KGS_BOT_PASSWORD}
    channel-id: ${KGS_CHANNEL_ID}